#!/bin/bash

REST_API_ID=$(aws apigateway get-rest-apis | jq --raw-output '.items[] | select(.name=="calculator").id')

echo "API URL: https://$REST_API_ID.execute-api.ap-southeast-2.amazonaws.com/Prod/"
echo ""
echo "Eg."
echo "https://$REST_API_ID.execute-api.ap-southeast-2.amazonaws.com/Prod/?left=4&right=2"
echo ""
