#!/bin/bash


## Gerardo: Set this to an S3 bucket in your AWS Account
BUCKET=sydney-summit-sam

# Will use my bucket when I run the code, otherwise will use yours :-)
if [[ $USER == "adstrick" ]]; then
    BUCKET=adams-artifacts
fi

export ARTIFACT_BUCKET=$BUCKET
echo "Artifact Bucket: $BUCKET"


## Step 0: Remove any existing CF stacks
echo "Deleting existing Stack..."
aws cloudformation delete-stack --stack-name calculator-add
aws cloudformation delete-stack --stack-name calculator-multiply
aws cloudformation wait stack-delete-complete --stack-name calculator-add
aws cloudformation wait stack-delete-complete --stack-name calculator-multiply

## Step 1a: Derive the ARN of the Calculator Validator
echo "Obtaining the ARN of the Validator..."
VALIDATOR_ARN=$(aws lambda get-function --function-name CodeDeployHook_SamSummitCalculatorValidator |jq --raw-output '.Configuration.FunctionArn')
echo "Validator ARN: $VALIDATOR_ARN"

# Step 1b: Update the demo1 template.yaml with the ARN of the validator
echo "Updating Demo1 Template with Validator ARN..."
rm -f ../demo1/template.yaml
cp template-demo1.yaml ../demo1/template.yaml
UPDATED_VALIDATOR_ARN="${VALIDATOR_ARN//\//\/}"
sed -i -e "s/##VALIDATORARN##/$UPDATED_VALIDATOR_ARN/g" ../demo1/template.yaml
rm -f ../demo1/template.yaml-e

## Step 1: Package + Deploy the API
echo "Running initial Package + Deploy for Demo1..."
cd ../demo1
aws cloudformation package --template-file template.yaml --s3-bucket $ARTIFACT_BUCKET --output-template-file ../temp/demo1-packaged.yaml
aws cloudformation deploy --template-file ../temp/demo1-packaged.yaml --stack-name calculator-add --capabilities CAPABILITY_IAM
cd ../pre-talk

## Step 2: Get URL for the API
echo "Retrieving the API URL..."
REST_API_ID=$(aws apigateway get-rest-apis | jq --raw-output '.items[] | select(.name=="calculator-add").id')
REST_URL="https://$REST_API_ID.execute-api.ap-southeast-2.amazonaws.com/Prod/"
echo "API URL:"
echo "$REST_URL"
echo ""
echo "Eg."
echo "${REST_URL}?left=4&right=2"
echo ""
export API_URL=$REST_URL
export ID=$REST_API_ID

## Step 3: Retrieve required information about the API
RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $REST_API_ID |jq --raw-output '.items[] | select(.path=="/").id')
ACCOUNT_NUMBER=$(aws sts get-caller-identity --output text --query 'Account')
METHOD_ARN="arn:aws:execute-api:ap-southeast-2:$ACCOUNT_NUMBER:$REST_API_ID/*/GET/"
export API_ID=$REST_API_ID
export API_RESOURCE_ID=$RESOURCE_ID
export ACCOUNT_NUMBER=$ACCOUNT_NUMBER
export METHOD_ARN=$METHOD_ARN

echo "Prep Script Complete"
echo "   REST API ID: $REST_API_ID"
echo "   RESOURCE ID: $RESOURCE_ID"
echo "    Method ARN: $METHOD_ARN"
echo " Validator ARN: $VALIDATOR_ARN"
echo "       API URL: $API_URL"
echo "  CURL Command: curl https://\$ID.execute-api.ap-southeast-2.amazonaws.com/Prod/?left=4&right=2"
