AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CalculatorValidator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: validate.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
              - "lambda:Get*"
              - "lambda:List*"
            Resource:
                !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'
      Runtime: nodejs12.x
      FunctionName: 'CodeDeployHook_SamSummitCalculatorValidator'
