#!/bin/bash

REST_API_ID=$(aws apigateway get-rest-apis | jq --raw-output '.items[] | select(.name=="awesome-calculator").id')
RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $REST_API_ID |jq --raw-output '.items[] | select(.path=="/").id')

ACCOUNT_NUMBER=$(aws sts get-caller-identity --output text --query 'Account')
METHOD_ARN="arn:aws:execute-api:ap-southeast-2:$ACCOUNT_NUMBER:$REST_API_ID/*/GET/"
GO_LAMBDA_ALIAS_ARN=$(aws lambda get-alias --function-name awesome-go-calculator --name live | jq --raw-output '.AliasArn')

export DUDE=sweet
export API_ID=$REST_API_ID
export API_RESOURCE_ID=$RESOURCE_ID
export ACCOUNT_NUMBER=$ACCOUNT_NUMBER
export METHOD_ARN=$METHOD_ARN
export LAMBDA_ALIAS_ARN=$GO_LAMBDA_ALIAS_ARN

echo ""
echo "REST API ID: $REST_API_ID"
echo "RESOURCE ID: $RESOURCE_ID"
echo " Method ARN: $METHOD_ARN"
echo " LAMBDA ARN: $GO_LAMBDA_ALIAS_ARN"
echo "    API URL: https://$REST_API_ID.execute-api.ap-southeast-2.amazonaws.com/Prod/"
echo ""
echo "Test URL:"
echo "https://$REST_API_ID.execute-api.ap-southeast-2.amazonaws.com/Prod/?left=4&right=2"
echo ""